Maesemen/stiff decode
UBCHREST/ablate pull request #194
Opened 2022-01-22 00:53 UTC by maesemen

fixes bug in twoPhaseAdvection. adds analytical decode state for perfect gas + stiffened gas case. adds integration test for 2D Sod problem.  closes #188

2022-01-22 02:05 UTC, jikembo reviewed
In the quadratic formula for roots in the decode state, PESTcmax was used for positive roots. However, petsmax is only for max of the two roots. What if the roots are negative or can we be sure both roots are always positive! You may want to have some caution there.

2022-01-22 18:04 UTC, mmcgurn requested changes
Look good!  I made one small change request.

2022-01-22 18:04 UTC, mmcgurn commented on ablateLibrary/eos/stiffenedGas.hpp
> +    PetscReal GetSpecificHeatCp() const { return parameters.Cp; }
There is already a GetComputeSpecificHeatConstantVolumeFunction and GetComputeSpecificHeatConstantVolumeContext to get the specific heat.  We may want to just use these interface functions to help future proof any calls.

2022-01-22 18:04 UTC, mmcgurn commented on tests/integrationTests/inputs/shockTube2Gas2D.yaml
> +    ts_max_time: 0.01
You dt is of fixed size and adapt is off.  This may be ok, but you have to make sure you don't step over the cfl constraint.

2022-01-24 16:20 UTC, mmcgurn approved these changes

2022-01-24 16:28 UTC, jikembo approved these changes

2022-01-24 18:04 UTC, merged