Maesemen/riemann stiff pstar
UBCHREST/ablate pull request #215
Opened 2022-02-03 20:39 UTC by maesemen

Fixes pstar convergence. closes #213

2022-02-03 20:58 UTC, jikembo approved these changes

2022-02-03 21:01 UTC, mmcgurn requested changes
For bugs like this, I think that it is a good idea to add a test case that would have caught this error.  Is there a test case you can add to catch this?

2022-02-03 21:30 UTC, maesemen commented
> For bugs like this, I think that it is a good idea to add a test case that would have caught this error. Is there a test case you can add to catch this?

It would take some work to figure out the conditions for the test case to catch this, but I did check with running a full simulation

2022-02-04 13:49 UTC, jikembo approved these changes

2022-02-04 14:25 UTC, merged