lesModel
UBCHREST/ablate pull request #364
Opened 2022-10-06 14:47 UTC by Rozie100

LES solver + associated tests are added.

2022-10-10 14:18 UTC, mmcgurn requested changes
It looks like there are more changed files than you intended.  Would you mind pulling the latest main and rebasing? Or if you have already used a merge workflow you may need to merge again?

2022-10-10 14:18 UTC, mmcgurn commented on src/finiteVolume/fluxCalculator/riemannStiff.cpp
Why was this file changed?

2022-10-10 14:18 UTC, mmcgurn commented on src/finiteVolume/processes/constantPressureFix.cpp
> +            if (conservedValues) {
I'm not sure why this file was changed?

2022-10-10 14:18 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.hpp
> +    struct DecodeDataStructGas {
I'm not sure why this file was changed?

2022-10-10 14:18 UTC, mmcgurn commented on tests/unitTests/finiteVolume/processes/twoPhaseEulerAdvectionTests.cpp
> +INSTANTIATE_TEST_SUITE_P(
I'm not sure why this file was changed?

2022-11-01 13:21 UTC, mmcgurn approved these changes

2022-11-01 13:21 UTC, mmcgurn commented on src/finiteVolume/processes/les.hpp
> +     * u = {"euler", "densityYi"}
These are good comments

2022-11-01 13:37 UTC, jikembo approved these changes
Looks fine.

2022-11-01 21:18 UTC, merged