move volume fraction from aux to input field
UBCHREST/ablate pull request #371
Opened 2022-11-01 15:34 UTC by maesemen

2022-11-02 18:51 UTC, mmcgurn requested changes
Thanks for starting this.  I have a few small requests and a question of uOff.  Are you still calling DecodeTwoPhaseEulerState when computing the fluxes? Does this recompute alpha still, or is that change part of another PR?

2022-11-02 18:51 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.cpp
> +    flow.RegisterRHSFunction(CompressibleFlowComputeEulerFlux, this, "euler", {"volumeFraction", "densityVF", "euler"}, {});
Would you mind changing these to a const variable like CompressibleFlowFields::EULER_FIELD?

2022-11-02 18:51 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.cpp
> +    const auto &flowEulerId = fvSolver.GetSubDomain().GetField("euler").id;  // constant instead of string for euler
Can you update this as well?

2022-11-02 18:51 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.cpp
> +    PetscCall(VecGetArrayRead(globFlowVec, &flowArray));
Why do you pull the flowArray twice?

2022-11-02 18:51 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.cpp
> +        uOff[0] = 3 + dim;  // alpha
I don't know if this is always true.  I think we need to get this from the fields.

2022-11-02 18:51 UTC, mmcgurn commented on tests/integrationTests/inputs/shocktube/shockTube1DSod_AirWater.yaml
> +    - &5
Would you changing these anchors to be names instead of numbers?

2022-11-02 18:51 UTC, mmcgurn commented on tests/integrationTests/inputs/volumeOfFluids/twoGasAdvectingDiscontinuity.yaml
> +      - !<!ablate::domain::modifiers::GhostBoundaryCells> ""
Would you mind updating this yaml file to get rid of the extra !< around each tag and using names instead of numbers for the anchors?

2022-11-03 13:08 UTC, jikembo approved these changes
Good change moving volume fraction to input field so that EOS can do its job.

2022-11-07 15:21 UTC, mmcgurn requested changes
Thanks for makes these changes.  I'm not sure if uOff is going to work but I added an example of something that I think will.

2022-11-07 15:21 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.cpp
> +    if (rhoAlphaEulerId > flowEulerId) {
These id orders are not always fixed and rhoAlphaEulerId may be before "Euler".  You should just pull the offset value directly from the field.

`PetscInt uOff[3] = {fvSolver.GetSubDomain().GetField("euler").offset, ..., ... }`

2022-11-07 15:21 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.cpp
> +    const auto &rhoAlphaEulerId = fvSolver.GetSubDomain().GetField("densityVF").id;
Can you use the variables such as CompressibleFlowFields::EULER_FIELD instead of strings here?

2022-11-07 15:21 UTC, mmcgurn commented on src/finiteVolume/processes/twoPhaseEulerAdvection.cpp
> +    // const int ALPHA_FIELD = 0; // new field
If ALPHA_Field is not used can we remove it?

2022-11-17 13:49 UTC, mmcgurn requested changes
Thanks for making these changes, I have just a few more comments.  How long does water gravity take to run?  We may want to use it as a regression test instead of integration so it can be larger.

2022-11-17 13:49 UTC, mmcgurn commented on tests/unitTests/finiteVolume/processes/twoPhaseEulerAdvectionTests.cpp
> +    PetscInt uOff[3] = {3 + params.dim /*alpha*/, 2 + params.dim /*rho1alpha1*/, 0 /*euler*/};
It may be worth doing another test where you change the order of the fields

2022-11-17 19:59 UTC, mmcgurn approved these changes

2022-11-17 20:07 UTC, merged