Memory Fix, Volumetric Limiter
UBCHREST/ablate pull request #398
Opened 2022-12-06 23:54 UTC by owenmylotte

Reduces the memory consumption of the radiation solver and protects the volumetric radiation from eos integration failures. Additional changes to enforce positivity in the absorption model.

2022-12-07 23:34 UTC, owenmylotte commented on src/eos/radiationProperties/zimmer.cpp
> +        *kappa = 0;
This enforces positive values out of the absorption model.

2022-12-09 20:59 UTC, mmcgurn requested changes

2022-12-09 20:59 UTC, mmcgurn commented on src/radiation/radiation.cpp
> -    EndEvent();
It looks like after the rebase we may be missing some Start/End events

2022-12-09 21:09 UTC, mmcgurn commented on src/radiation/radiation.cpp
> -    EndEvent();
I added back the events and pushed to the PR branch.

2022-12-09 21:24 UTC, owenmylotte commented
Thank you for fixing this!

2022-12-30 17:24 UTC, mmcgurn commented
This will be replaced with an updated PR using PetscSF for rad.

2022-12-30 17:24 UTC, closed without merging