Virtual TCP and Arbitrary Surface Radiation Monitor
UBCHREST/ablate pull request #433
Opened 2023-02-09 20:41 UTC by owenmylotte

Allows the creation of windows or virtual plates to calculate the radiation that would be detected by a plate or camera. Multiple ray tracing inputs can be input to the same monitor to allow for multiple outputs of different ray tracing behaviors or absorption models.

2023-02-10 00:01 UTC, owenmylotte commented
I finished this for now and added the additional check. I still need to make sure that the integration test is in and comparing properly.

2023-02-13 18:36 UTC, mmcgurn requested changes
Thanks.  This looks great!  I have two small nick-picky things.

2023-02-13 18:36 UTC, mmcgurn commented on src/monitors/radiationFlux.cpp
> +    DMPlexFilter(solverIn->GetSubDomain().GetDM(), radiationFluxRegionLabel, 1, &fluxDm) >> utilities::PetscUtilities::checkError;
Instead of using one here, you can use the region value you pulled on line 16.  Most often it is 1, but not always.

2023-02-13 18:36 UTC, mmcgurn commented on src/monitors/radiationFlux.cpp
> +            for (int i = 0; i < int(radiation.size()); i++) {
I don't see any reason to cast to an int here, I would std::size_t instead of int.

2023-02-13 18:36 UTC, mmcgurn commented on tests/integrationTests/inputs/monitors/radiationFlux.yaml
> +---
this input looks like one that ablate had already processed?  Do you the the original that used text based anchors?

2023-02-13 19:45 UTC, mmcgurn approved these changes

2023-02-15 15:15 UTC, merged