Batch processing of Chemtab Source Computation
UBCHREST/ablate pull request #506
Opened 2023-12-07 19:16 UTC by profPlum

I've manually verified it produces the same results as before and it appears to now be twice as fast.

2023-12-19 14:24 UTC, mmcgurn requested changes
I have some questions about the batch processing.

2023-12-19 14:24 UTC, mmcgurn commented on src/eos/chemTab.cpp
> +// void ablate::eos::ChemTab::ChemTabModelComputeFunction(const PetscReal density[], const PetscReal*const*const densityProgressVariables,
Can you remove this dead code?

2023-12-19 14:24 UTC, mmcgurn commented on src/eos/chemTab.cpp
> +    TF_Tensor *input_tensor = TF_NewTensor(TF_FLOAT, dims, (int)ndims, input_data, ndata, &NoOpDeallocator, nullptr);
I think we might be able to save time by reusing the memory/tensor object?  We could do that by having the ChemTabSourceCalculator own the tensor.  The ChemTabSourceCalculator instance is always the same batch size.

2023-12-19 14:24 UTC, mmcgurn commented on src/eos/chemTab.cpp
> +    // TODO: consider/optimize the problem that is likely requires loop to copy these arrays into TF inputs??
If the ChemTabSourceCalculator instance owned the tensor, you could copy directly into the tensor here.

2023-12-19 14:24 UTC, mmcgurn commented on src/eos/chemTab.cpp
> +void ablate::eos::ChemTab::extractModelOutputsAtPoint(const PetscReal density, PetscReal *densityEnergySource, PetscReal *densityProgressVariableSource, PetscReal *densityMassFractions,
Would you mind changing the names to match the google style case? https://ablate.dev/content/development/Formatting.html

2023-12-19 14:24 UTC, mmcgurn commented on src/eos/chemTab.hpp
> +    // Batched Version of above
Could you change this comment to work with doxygen for the method signature? Is this method used anywhere or tested?

2023-12-19 18:38 UTC, profPlum commented on src/eos/chemTab.cpp
> +// void ablate::eos::ChemTab::ChemTabModelComputeFunction(const PetscReal density[], const PetscReal*const*const densityProgressVariables,
Sure

2025-01-28 19:55 UTC, klbudzin approved these changes

2025-01-28 19:58 UTC, merged