Pakserep/inertial particle bug
UBCHREST/ablate pull request #56
Opened 2021-05-21 23:29 UTC by pakserep

Inertial particles added with their google test for 3 different test cases.

2021-05-22 00:01 UTC, pakserep commented
Hi @mmcgurn 
Could you please review this PR? it shows one of the checks is failing though! Should I do something to fix it? thanks.

2021-05-24 11:44 UTC, mmcgurn commented
@pakserep It looks like there were a lot of changes between when you started working on the branch and now.  It won't let you merge in the code until you resolve.  I like to use git rebase https://docs.github.com/en/github/getting-started-with-github/using-git/about-git-rebase .  My favorite way to git rebase is to use GitHub Desktop rebating https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch#rebasing-your-project-branch-onto-another-branch

2021-05-24 11:54 UTC, mmcgurn requested changes
@pakserep Thanks for putting in this PR! and all of the hard work that goes into it.  I think that there is a bug in replacing newer code and you may need to rebase your code, but overall it looks good!  Would you also mind adding a little documentation about how particle system/equations? I'd be happy to help.

2021-05-24 11:54 UTC, mmcgurn commented on ablateCore/particles/particleInertial.c
> +
If you get a chance, would you mind removing the extra spaces in the files?

2021-05-24 11:54 UTC, mmcgurn commented on ablateCore/particles/particles.c
> -    PetscViewer viewer;
I think that you are introducing old code here.  I think that putting back this old code may result in some bugs.

2021-05-24 19:34 UTC, pakserep commented
hi @mmcgurn, thanks for taking the time and reviewing the PR and thanks for the comments. I rebased my feature branch (pakserep/inertialParticle-bug) onto the updated main branch (upstream) and pushed my changes from cloned to my fork. it sees the PR is updated and reflecting the new commits. Please let me know if this resolves the issues. Once this is resolved I will do another PR for documentation, if that's ok. Thanks.

2021-05-25 01:48 UTC, mmcgurn approved these changes

2021-05-25 01:49 UTC, mmcgurn commented
@pakserep You should now be good to squash and merge.  Make sure you select Squash and Merge option.

2021-05-25 15:48 UTC, merged